const footer = {
  about: {
    heading: 'About SafeFamily',
    tagline: 'Protecting families, one device at a time.',
  },
  contact: {
    heading: 'Contact Us',
    address: 'Address',
    phone: 'Phone',
    support: 'Support',
    email: 'Email',
    website: 'Website',
  },
  legal: {
    heading: 'Legal',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    copyright: '© {{year}} {{legalName}}. All rights reserved.',
  },
  /**
   * Labels for footer navigation links. Keys must match FooterNavKey in footerNav.ts.
   * Only entries for keys with visible: true in footerNav are rendered.
   */
  links: {
    about:   'About',
    contact: 'Contact',
    privacy: 'Privacy Policy',
    terms:   'Terms of Service',
    help:    'Help',
  },
  print: {
    generatedBy: 'Generated by {{name}}',
    generatedAt: 'Generated: {{date}}',
    confidential: 'This document is confidential and intended for the recipient only.',
  },
} as const

export default footer
