/**
 * reports.api.ts
 *
 * API layer for the Reports feature.
 *
 * NOTE: The backend does not yet expose a dedicated /api/reports endpoint.
 * The functions below use clearly-marked MOCK data so the real implementation
 * can be dropped in by replacing the body of each function with an apiClient
 * call — no other file needs to change.
 *
 * When the real API is ready:
 *   1. Remove the MOCK DATA section below.
 *   2. Uncomment (or write) the apiClient.get / apiClient.get calls.
 *   3. Adjust the Report interface in reports.types.ts if the shape differs.
 */
import type { Report } from './reports.types'

// ─── MOCK DATA (replace with real API calls) ──────────────────────────────────

const MOCK_REPORTS: Report[] = [
  {
    id: 'rep-001',
    type: 'Assessment',
    title: 'Family Risk Assessment — March 2026',
    description: 'Full risk assessment covering account security, device hygiene, backup, privacy and scam readiness.',
    generatedAt: '2026-03-21T10:00:00Z',
    contextLabel: 'Overall score: 62 / 100 · Medium Risk',
    downloadUrl: null,
    body: `## Family Risk Assessment — March 2026

**Overall Score:** 62 / 100 — Medium Risk

### Category Scores
| Category | Score |
|---|---|
| Account Security | 55 |
| Device Hygiene | 70 |
| Backup & Recovery | 45 |
| Privacy & Sharing | 80 |
| Scam Readiness | 60 |

### Immediate Actions
1. Enable two-factor authentication on all email and banking accounts.
2. Update devices running end-of-life operating systems.
3. Set up automatic cloud backups for all family devices.

---
*Generated by SafeFamily · ${new Date('2026-03-21').toLocaleDateString()}*`,
  },
  {
    id: 'rep-002',
    type: 'Incident',
    title: 'Incident Report: Phishing Attempt',
    description: 'Action plan generated after a phishing attempt was reported. Includes immediate steps and longer-term hardening advice.',
    generatedAt: '2026-03-15T14:22:00Z',
    contextLabel: 'Severity: High · Phishing Attempt',
    downloadUrl: null,
    body: `## Incident Report: Phishing Attempt

**Reported:** 15 March 2026  
**Severity:** High  
**Type:** Phishing Attempt

### What Happened
A family member received a suspicious email impersonating their bank, requesting login credentials.

### Immediate Action Plan
1. Do not click any links in the suspicious message.
2. Report the phishing email to your email provider using the "Report Phishing" option.
3. Change the password on the potentially affected account immediately.
4. Enable two-factor authentication (2FA) on the account if not already active.
5. Alert other family members to watch for similar messages.

### Longer-Term Hardening
- Use a password manager to generate unique credentials per service.
- Enable login alerts on banking and email accounts.
- Bookmark your bank's official website rather than following email links.

---
*Generated by SafeFamily · ${new Date('2026-03-15').toLocaleDateString()}*`,
  },
  {
    id: 'rep-003',
    type: 'FamilyReset',
    title: 'Family Digital Reset — Session Summary',
    description: 'Summary of the Family Digital Reset session completed with a SafeFamily advisor. Includes completed actions and follow-up checklist.',
    generatedAt: '2026-03-10T09:00:00Z',
    contextLabel: 'Package: Family Digital Reset · Online',
    downloadUrl: null,
    body: `## Family Digital Reset — Session Summary

**Session Date:** 10 March 2026  
**Channel:** Online video call  
**Advisor:** SafeFamily Team

### Actions Completed During Session
- ✅ Password audit — 14 weak passwords updated
- ✅ 2FA enabled on Gmail, Apple ID, and banking accounts
- ✅ Device location tracking verified on all family phones
- ✅ Privacy settings reviewed on social media accounts

### Follow-Up Checklist
- [ ] Enable automatic OS updates on the family laptop
- [ ] Set up a shared password manager family vault
- [ ] Discuss safe-sharing guidelines with children

### Next Steps
Your next recommended check-in is in **3 months**. Book a follow-up session anytime from the Bookings page.

---
*Generated by SafeFamily · ${new Date('2026-03-10').toLocaleDateString()}*`,
  },
  {
    id: 'rep-004',
    type: 'Assessment',
    title: 'Family Risk Assessment — January 2026',
    description: 'Baseline risk assessment completed at onboarding.',
    generatedAt: '2026-01-08T11:30:00Z',
    contextLabel: 'Overall score: 41 / 100 · High Risk',
    downloadUrl: null,
    body: `## Family Risk Assessment — January 2026

**Overall Score:** 41 / 100 — High Risk

### Category Scores
| Category | Score |
|---|---|
| Account Security | 30 |
| Device Hygiene | 55 |
| Backup & Recovery | 20 |
| Privacy & Sharing | 65 |
| Scam Readiness | 35 |

### Immediate Actions
1. Enable 2FA on all accounts immediately.
2. Replace all reused passwords with unique strong ones.
3. Configure automatic backup on all devices.
4. Review and tighten privacy settings on social accounts.

---
*Generated by SafeFamily · ${new Date('2026-01-08').toLocaleDateString()}*`,
  },
]

// ─── API functions (swap these with real apiClient calls when ready) ──────────

export const reportsApi = {
  /**
   * GET /api/reports  (MOCKED)
   * Returns all reports for the authenticated family.
   */
  getReports(): Promise<Report[]> {
    // TODO: return apiClient.get<Report[]>('/api/reports')
    return Promise.resolve([...MOCK_REPORTS])
  },

  /**
   * GET /api/reports/:id/download  (MOCKED)
   * Returns a Blob suitable for triggering a browser download.
   */
  downloadReport(id: string): Promise<Blob> {
    // TODO: return apiClient.get<Blob>(`/api/reports/${id}/download`, { responseType: 'blob' })
    const report = MOCK_REPORTS.find((r) => r.id === id)
    const text = report
      ? `${report.title}\n\n${report.body}`
      : 'Report not found.'
    return Promise.resolve(new Blob([text], { type: 'text/plain' }))
  },
}
